print ("My personal info :")
print("name is Nsreen Nashaat")
print("age is 22")
print("Communication and Electronics Department")
print("Graduation year is 2024")
print("favorite team is Hardware team")
